### ISSUE TITLE
Some fixes for stan_utility

### ISSUE THREAD

**Issue by ahartikainen** [betanalpha/jupyter_case_studies#4]
Hi, here are some comments for the `stan_utility.py`.

### python 2
Use `from __future__ import division, print_function` for py2 compatibility
If `division` is not imported all the division `n/N` will result to 0.

### precision when printing
In prints use formatter to control the number of digits (e.g. 2)
    
    "{:.2f}%".format(n/N)

### _by_chain -function (also see the next subject)
equals to

    numpy.swapaxes(ef, 0, 1)

### reshaping extract
lines 48 and 49
    
    ef = _by_chain(ef)
    ef = ef.reshape(-1, len(ef[0][0]))

equals to

    ef = ef.reshape(-1, ef.shape[-1], order='F')

### line 53
no need to call extract()

    fit.extract().keys() == fit.sim['pars_oi']

### line 56
should this line save the result? 

    shaped[param_name] = shaped[param_name].reshape(*([-1] + dim))

**Comment by seantalts** [comment]
Hey, these all look like great fixes (assuming they all work pretty much as described - I'm a little light on Python 3 and numpy). Any reason you didn't want to make a pull request with them? 

Couple comments:
* not sure what precision @betanalpha would want to be printed
* not sure why the code works with Python 2 given the `division` and `reshape` comments you made - seems like those would break it

**Comment by betanalpha** [comment]
3 significant figures should be adequate.

**Comment by ahartikainen** [comment]
Hi

I can make PR. I just first wanted your opinion.

The division problem comes with `int / int = int`. Values from extract are `float` --> `float/int=float`

**Comment by betanalpha** [comment]
Sean is the local Python expert so if the PR looks good to him
then I’ll happily merge it.  Per his response, can you validate 
that the changes would work for both Python 2 and Python 3?

It would also be great to have these functions in PyStan if
possible, but that would be up to you and Allen.  Please feel
free to take them verbatim if desired.

**Comment by seantalts** [comment]
Cool, yeah so maybe we don't need the `division` import. Not sure about the reshape thing - one of us will need to test if that either 1) wasn't necessary and can be deleted or 2) was necessary and broken before and should be rewritten as you describe.

**Comment by ahartikainen** [comment]
These changes are not necessary.
