### ISSUE TITLE
PyStan Diagnostics functions, such as Stan_utility, in any pip package?

### ISSUE THREAD

**Issue by heoa** [betanalpha/jupyter_case_studies#5]
I could find the following functions in the case studies, I am wondering why they are not gathered in any package. So does there exist any Python package with similar diagnostic tools for PyStan?

https://github.com/betanalpha/jupyter_case_studies/blob/master/pystan_workflow/stan_utility.py

**Comment by betanalpha** [comment]
Some functionality will be included in the next version of PyStan.  The diagnostics evolve faster than the releases.
