### ISSUE TITLE
Pip release - pip installable

### ISSUE THREAD

**Issue by ahartikainen** [betanalpha/jupyter_case_studies#6]
Do you think `stan_utility` could be put to pypi?

This would enable users to pip install it. Otherwise this could be installable from git too. Just needs same structure as pypi thing (setup.py + some __init__)

(I still think all the updates here should go to pystan too).

This would enable you to pin down version and show it where these are used.

**Comment by betanalpha** [comment]
`stan_utility.py` currently serves as a demonstration for how to implement my recommended workflow in PyStan, and has not been extensively tested for the range of systems that PyStan currently is.    I just can't guarantee that elements won't change as I continue to update the workflow with evolving research.  

That said, the code is BSD3'd and anyone is welcome to merge it into PyStan or wrap it into a pip installable with those caveats in mind.  I'm happy to assist anyone interested in either!
