### ISSUE TITLE
stan_cache

### ISSUE THREAD

**Issue by s144117** [betanalpha/jupyter_case_studies#7]
Hi,

When I installed pystan the first time I ran into problems with a missing stan_cache.
I solved it by simply changing the code in utils.py

But now I have installed on the institutes server (requested it). Again I meet the same problem, while using `compile_model`:
No such file or directory: '/home/micmad/.stan_cache/cached-model-c4ed8c57c14f2eabbd4599b428df4a4c.pkl'

I do not have root access, making it hard to manually change the code. Is there a way to specify a location as your cache?

Thanks in advance
Michael

**Comment by betanalpha** [comment]
The pickle file is automatically saved to the current working directory.  It's straightforward to modify the script to change that to a hardcoded directory or add another argument with a variable base path.

I'm not sure how the quoted error can happen as the only attempt to open the cache file is in a try block whose exception is explicitly caught, so there's no way that error should propagate to the user.  Perhaps more relevantly the script was written to be run interactively and there is currently no guaranteed support on clusters.
